"""Dynamic Airflow DAG generator for ETL Agent-produced Spark pipelines.

Usage (from the orchestrator):
    from orchestration.airflow_dag_template import generate_dag
    dag_code = generate_dag(dag_id="etl_story_001", script_gcs_uri="gs://...", story_id="STORY-001")

The generated DAG follows this task graph:
    gcs_file_sensor → submit_dataproc_job → check_job_status → data_quality_check → notify_complete
"""

from __future__ import annotations

import textwrap


def generate_dag(
    dag_id: str,
    script_gcs_uri: str,
    story_id: str,
    schedule_interval: str = "@daily",
    dataproc_cluster: str = "etl-agent-cluster",
    gcp_project: str = "{{ var.value.gcp_project_id }}",
    gcp_region: str = "us-central1",
    input_gcs_path: str = "",
    output_gcs_path: str = "",
    owner: str = "etl-agent",
) -> str:
    """Generate a complete Airflow DAG Python file as a string.

    Args:
        dag_id: Unique identifier for the Airflow DAG.
        script_gcs_uri: GCS URI of the PySpark script to run.
        story_id: The DevOps story ID this DAG was generated from.
        schedule_interval: Cron expression or preset (default @daily).
        dataproc_cluster: Name of the Dataproc cluster.
        gcp_project: GCP project ID (can use Airflow variable).
        gcp_region: GCP region for Dataproc.
        input_gcs_path: Source data path (passed to Spark script as arg).
        output_gcs_path: Output data path (passed to Spark script as arg).
        owner: DAG owner label in Airflow UI.

    Returns:
        A string containing a complete, valid Airflow DAG Python file.
    """
    return textwrap.dedent(f'''\
        """
        AUTO-GENERATED Airflow DAG
        Story: {story_id}
        DAG ID: {dag_id}
        Generated by: Autonomous ETL Agent
        DO NOT EDIT MANUALLY — re-generate via the ETL Agent API.
        """

        from __future__ import annotations

        from datetime import datetime, timedelta

        from airflow import DAG
        from airflow.operators.empty import EmptyOperator
        from airflow.providers.google.cloud.operators.dataproc import (
            DataprocSubmitJobOperator,
        )
        from airflow.providers.google.cloud.sensors.gcs import GCSObjectsWithPrefixExistenceSensor
        from airflow.utils.trigger_rule import TriggerRule

        # ---------------------------------------------------------------------------
        # DAG configuration
        # ---------------------------------------------------------------------------

        DAG_ID = "{dag_id}"
        STORY_ID = "{story_id}"
        SCRIPT_GCS_URI = "{script_gcs_uri}"
        GCP_PROJECT = "{gcp_project}"
        GCP_REGION = "{gcp_region}"
        DATAPROC_CLUSTER = "{dataproc_cluster}"
        INPUT_PATH = "{input_gcs_path}"
        OUTPUT_PATH = "{output_gcs_path}"

        DEFAULT_ARGS = {{
            "owner": "{owner}",
            "depends_on_past": False,
            "email_on_failure": True,
            "email_on_retry": False,
            "retries": 2,
            "retry_delay": timedelta(minutes=5),
        }}

        PYSPARK_JOB = {{
            "reference": {{"project_id": GCP_PROJECT}},
            "placement": {{"cluster_name": DATAPROC_CLUSTER}},
            "pyspark_job": {{
                "main_python_file_uri": SCRIPT_GCS_URI,
                "args": [
                    "--input-path", INPUT_PATH,
                    "--output-path", OUTPUT_PATH,
                ],
                "properties": {{
                    "spark.sql.adaptive.enabled": "true",
                    "spark.sql.adaptive.coalescePartitions.enabled": "true",
                }},
            }},
        }}

        # ---------------------------------------------------------------------------
        # DAG definition
        # ---------------------------------------------------------------------------

        with DAG(
            dag_id=DAG_ID,
            description=f"Auto-generated ETL pipeline from story {{STORY_ID}}",
            schedule_interval="{schedule_interval}",
            start_date=datetime(2026, 1, 1),
            default_args=DEFAULT_ARGS,
            catchup=False,
            max_active_runs=1,
            tags=["auto-generated", "etl", STORY_ID],
        ) as dag:

            start = EmptyOperator(task_id="start")

            # Wait for source data to arrive in GCS before submitting job
            check_source_data = GCSObjectsWithPrefixExistenceSensor(
                task_id="check_source_data",
                bucket=INPUT_PATH.replace("gs://", "").split("/")[0] if INPUT_PATH else "placeholder",
                prefix="/".join(INPUT_PATH.replace("gs://", "").split("/")[1:]) if INPUT_PATH else "",
                timeout=3600,
                poke_interval=60,
                mode="reschedule",
            )

            submit_spark_job = DataprocSubmitJobOperator(
                task_id="submit_spark_job",
                job=PYSPARK_JOB,
                region=GCP_REGION,
                project_id=GCP_PROJECT,
                gcp_conn_id="google_cloud_default",
            )

            end = EmptyOperator(
                task_id="end",
                trigger_rule=TriggerRule.ALL_DONE,
            )

            # Task dependencies
            start >> check_source_data >> submit_spark_job >> end
    ''')


# ---------------------------------------------------------------------------
# CLI — generate a DAG file directly from command line
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import argparse
    import sys

    parser = argparse.ArgumentParser(description="Generate an Airflow DAG for an ETL pipeline.")
    parser.add_argument("--dag-id", required=True)
    parser.add_argument("--script-gcs-uri", required=True)
    parser.add_argument("--story-id", required=True)
    parser.add_argument("--schedule", default="@daily")
    parser.add_argument("--output", default="-", help="Output file path (- for stdout)")
    args = parser.parse_args()

    dag_code = generate_dag(
        dag_id=args.dag_id,
        script_gcs_uri=args.script_gcs_uri,
        story_id=args.story_id,
        schedule_interval=args.schedule,
    )

    if args.output == "-":
        sys.stdout.write(dag_code)
    else:
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(dag_code)
        print(f"DAG written to {args.output}")
